INSERT INTO `grades` VALUES (10,'Infantil',1),
                            (11, '1er de primària',1),
                            (12, '2on de primària',1),
                            (13, '3er de primària',1),
                            (14, '4t de primària',1),
                            (15, '5è de primària',1),
                            (16, '6è de primària',1),
                            (17, '1er de ESO',1),
                            (18, '2on de ESO',1),
                            (19, '3er de ESO',1),
                            (20,'4t de ESO',1),
                            (21,'1er de batxillerat',1),
                            (22,'2on de batxillerat',1),
                            (23,'FP grau mig',1),
                            (24,'FP grau superior',1),
                            (99,'Altres (de lectura, diccionaris, ...)',1);
